import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('plan submission is cancellable and stale responses cannot replace a restarted flow', async () => {
  const app = await readFile(new URL('./AdvisorApp.tsx', import.meta.url), 'utf8')
  const api = await readFile(new URL('./client/api.ts', import.meta.url), 'utf8')
  assert.match(app, /submissionRevision = useRef/)
  assert.match(app, /submissionAbort = useRef<AbortController/)
  assert.match(app, /controller\.signal\.aborted \|\| submissionRevision\.current !== requestRevision/)
  assert.match(app, /submissionAbort\.current\?\.abort\(\)[\s\S]*setPath\(nextPath\)/)
  assert.match(app, /aria-busy=\{isSubmitting\}/)
  assert.match(api, /signal: storage\.signal/)
})

test('invalid navigation focuses a control and sections expose their requirements', async () => {
  const app = await readFile(new URL('./AdvisorApp.tsx', import.meta.url), 'utf8')
  assert.match(app, /selectSection\(activeSection, true\)/)
  assert.match(app, /selectSection\(first\.id, true\)/)
  assert.match(app, /aria-describedby=\{issues\.length \? `ap-section-\$\{id\}-issues`/)
  assert.match(app, /querySelector<HTMLElement>\('textarea, input:not\(\[type="hidden"\]\), select, button'\)/)
})

test('consumer trust copy, privacy, terms, and portable plan output are present', async () => {
  const app = await readFile(new URL('./AdvisorApp.tsx', import.meta.url), 'utf8')
  const privacy = await readFile(new URL('./privacy/page.tsx', import.meta.url), 'utf8')
  const terms = await readFile(new URL('./terms/page.tsx', import.meta.url), 'utf8')
  const css = await readFile(new URL('./ai-path.css', import.meta.url), 'utf8')
  assert.match(app, /Don’t enter passwords, API keys/)
  assert.match(app, /href="\/ai-path\/privacy"/)
  assert.match(app, /href="\/ai-path\/terms"/)
  assert.match(app, /window\.print\(\)/)
  assert.match(privacy, /Do not enter passwords, API keys/)
  assert.match(privacy, /up to 90 days/)
  assert.match(terms, /intended for adults/)
  assert.match(css, /@media print/)
})

test('the diagnostic tells the truth about typing, microphone testing, processing, and expected duration', async () => {
  const app = await readFile(new URL('./AdvisorApp.tsx', import.meta.url), 'utf8')
  const css = await readFile(new URL('./ai-path.css', import.meta.url), 'utf8')
  assert.match(app, /Type your answers/)
  assert.doesNotMatch(app, /<strong>Speak or type<\/strong>/)
  assert.match(app, /Optional microphone test only\. It does not transcribe or submit audio\./)
  assert.match(app, /Test microphone locally/)
  assert.match(app, /className="ap-ds-fieldMic"/)
  assert.match(css, /\.ap-ds-fieldMic svg/)
  assert.doesNotMatch(app, /className="ap-ds-micTool"/)
  assert.match(app, /(?:About|Allow) 10–15 minutes/)
  assert.match(app, /Typed answers are sent to AI Path to create this plan/i)
  assert.match(app, /not saved to your account unless you choose Save/i)
  assert.match(app, /provider-backed question tailoring is enabled, an AI provider may process/i)
  assert.match(app, /Saved answers are kept for up to 90 days/i)
})

test('foundation options use professional labels and data is multi-select', async () => {
  const app = await readFile(new URL('./AdvisorApp.tsx', import.meta.url), 'utf8')
  assert.match(app, /I have not written code/)
  assert.match(app, /I can edit simple examples/)
  assert.match(app, /I can build small scripts/)
  assert.match(app, /I build and debug software/)
  assert.doesNotMatch(app, /I have not coded/)
  assert.doesNotMatch(app, /\"Modify examples\"/)
  assert.match(app, /Documents, PDFs, and web pages/)
  assert.match(app, /Spreadsheets and simple tables/)
  assert.match(app, /Databases, SQL, or dashboards/)
  assert.match(app, /Data pipelines or ML models/)
  assert.match(app, /<MultiChoice[\s\S]*label="Data"/)
  assert.doesNotMatch(app, /<ChoiceGroup compact label="Data"/)
})

test('result UI renders the executive summary, structured first step, starter artifact, and honest resource allocation', async () => {
  const app = await readFile(new URL('./AdvisorApp.tsx', import.meta.url), 'utf8')
  assert.match(app, /result\.summary\.recommendation/)
  assert.match(app, /result\.summary\.decisionGate/)
  assert.match(app, /result\.firstStep\.task/)
  assert.match(app, /result\.firstStep\.doneWhen/)
  assert.match(app, /result\.starterArtifact\.title/)
  assert.match(app, /result\.starterArtifact\.fields\.map/)
  assert.match(app, /resource\.week/)
  assert.match(app, /formatMinutes\(resource\.planMinutes\)/)
})
